### PR TITLE
Fix event-stream dependency for antora by regenerating package-lock.json

### PR DESCRIPTION
**Pull request by devurandom**
See-Also: https://github.com/nrepl/nrepl.org/pull/2#issuecomment-448410831
See-Also: https://gitlab.com/antora/antora/issues/350#note_126297615

### CODE REVIEW

**Comment by bbatsov** [comment]
@devurandom Any idea why the diff is so big? I'm afraid my knowledge of npm is quite limited.

**Comment by devurandom** [comment]
I am not a NodeJS expert myself, but AFAIK the `package-lock.json` records all the transitive dependencies that in one way or another (i.e. transitively via any of the dependencies of yours) end up being used by your project. Since NodeJS projects are often composed out of hundreds of libraries, and any change in any of those libraries influences every other library depending on them, even if that dependency is only transitively, and because usually these dependencies are not locked to precise versions as in e.g. Leiningen, but to loose ranges of versions, just regenerating the `package-lock.json` at another time will show you a very different picture of the NodeJS ecosystem.

**Review by SevereOverfl0w — APPROVED** [review]

**Review by SevereOverfl0w — APPROVED** [review]

**Comment by bbatsov** [comment]
I guess that now that #2 is merged we can close this one. (see #2 already has this commit)

**Comment by devurandom** [comment]
> I guess that now that #2 is merged we can close this one. (see #2 already has this commit)

Oups, that was a mistake. Should have been two separate PRs.

**Pull request closed without merging**
