### PR TITLE
Add asciidoc-based documentation

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
Preview available at https://severeoverfl0w.github.io/nREPL.org/nrepl/index.html.
Currently built from my fork of nREPL.

### CODE REVIEW

**Comment by bbatsov** [comment]
I can't see the preview - says "Page not found" there.

**Comment by bbatsov** [comment]
Hmm, https://severeoverfl0w.github.io/nREPL.org/nrepl/0.4.5/index.html works (saw this on Slack). 

Might be good to put some instructions about building/publishing the site in the readme as well - e.g. a list to the manual if that info is in it. 

Overall things look good to me. Great work so far!

**Comment by SevereOverfl0w** [comment]
because case sensitivity is important, and I am silly, https://severeoverfl0w.github.io/nREPL.org/ is the real slim shady.

**Comment by bbatsov** [comment]
@SevereOverfl0w Got it. So, two small questions. Or three. :-)

* Why is there a 0.5 version? 
* Can we have some expanding menus on the left so it'd be easier to navigate to (second-level) subheadings?
* Is there anything else needed before we can publish this?

**Comment by SevereOverfl0w** [comment]
- 0.5 was me testing that the version bumping works. I created a `b` tag on my fork which had the version increased. In this area we should track https://gitlab.com/antora/antora/issues/296 as it will make life easier.
- We can generate a table of contents at the top of the page. I suspect antora has an open issue for generating it like rtfm does, but I couldn't find it. I've reached out to the Antora team on gitter. We could also do it manually, but blugh.
- I think nrepl/nREPL will need to tag a release with the version in. 0.4.5 currently resolves to a repo without the antora.yml in. I could add `master` to branches, which is probably generally sensible.

I'll get back to you once I have an answer regarding 2, probably via a top of the page toc, but also hopefully an issue reference. I'll also have a think about getting 0.4.5 up there, maybe we should tag a 0.4.5-doc or something.

**Comment by bbatsov** [comment]
> I'll get back to you once I have an answer regarding 2, probably via a top of the page toc, but also hopefully an issue reference. I'll also have a think about getting 0.4.5 up there, maybe we should tag a 0.4.5-doc or something.

We can also just retag 0.4.5 I guess. There are no code changes if I recall correctly, so it's not a big deal. It'd be nice to add the `master` branch indeed - especially if we want to publish doc updates automatically via travis or whatever.

**Comment by SevereOverfl0w** [comment]
https://gitlab.com/antora/antora-ui-default/merge_requests/54/diffs looks like the concept is going to happen, the implementation is still tbd. We can import this though I believe.

**Comment by bbatsov** [comment]
@SevereOverfl0w That looks great to me! If you can import this easily let's go for it.

**Comment by bbatsov** [comment]
I also just noticed that deleting the md files killed https://nrepl.readthedocs.io/en/latest/, so I guess we should just publish whatever we have currently and tweak things later.

**Comment by bbatsov** [comment]
Btw, is there some way to enable syntax highlighting for the code examples? Seems to me there's none right now.

**Comment by bbatsov** [comment]
That's also slightly weird, as those look the same in GitHub:

image

**Comment by SevereOverfl0w** [comment]
It looks like the first block is being mis-detected as nginx, the second is being detected as css.

As you noted, the highlight.js build being used doesn't include Clojure.  So 2 fixes needed:

- Explicitly mark the code blocks around commands
- Add highlight.js css for Clojure

I'll see if I can squeeze these in during the next 40 minutes.

**Comment by SevereOverfl0w** [comment]
Pull request open at nrepl/nREPL to work around the lack of language on those blocks, fixing them. Apparently this is an anti-feature of highlight.js that can't be disabled.

There's some future plans to try atom's highlighter, but it's not packaged yet.

The default-ui now contains clojure the language, so my next build after their CI has run will fix this.

**Comment by bbatsov** [comment]
> Pull request open at nrepl/nREPL to work around the lack of language on those blocks, fixing them. Apparently this is an anti-feature of highlight.js that can't be disabled.

I don't see it. :-)

> The default-ui now contains clojure the language, so my next build after their CI has run will fix this.

Excellent!

**Comment by SevereOverfl0w** [comment]
Sorry. I forgot to hit "enter". PR opened. I also pushed to the URL https://severeoverfl0w.github.io/nREPL.org/index.html with the new UI built against it.

**Pull request merged**
